// <auto-generated />
using System;
using BlogWebsite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118134517_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about tech and gadgets",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Health tips and news",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Travel guides and experiences",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "People lifestyle and stuffs.",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports media and all.",
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great article! Learned a lot about tech.",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Very helpful health tips, thanks!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Content = "I want to visit these places ASAP!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserName = "Charlie"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Theon",
                            CategoryId = 1,
                            Content = "As we head into late 2025 and look toward 2026, technology continues its rapid evolution, driven primarily by advancements in artificial intelligence, sustainable computing, and connectivity. Agentic AI—systems that autonomously plan, reason, and execute multi-step tasks—has moved from hype to enterprise reality, with Deloitte and Gartner highlighting how organizations are embedding these agents into workflows for everything from customer service to supply chain optimization. Multimodal AI, processing text, images, video, and audio seamlessly, powers more intuitive tools like real-time translation and creative assistants. Edge computing reduces latency for IoT and autonomous systems, while private 5G/6G networks enable secure industrial applications. Sustainability is huge: AI's energy demands push adoption of nuclear-powered data centers and efficient algorithms. Quantum computing edges closer with error-corrected qubits from IBM and Google, promising breakthroughs in drug discovery and optimization. Cybersecurity evolves with AI-driven threat detection amid rising deepfake risks. For developers and businesses, the key is building 'change fitness'—rapid adaptation through hybrid clouds, upskilling, and ethical AI governance. 2025-2026 marks the shift where tech becomes a true strategic partner, not just a tool.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Latest Tech Trends 2025"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ada Lovelace",
                            CategoryId = 1,
                            Content = "2026 promises the deepest phase of the AI revolution yet. Agentic AI will dominate, acting as autonomous digital colleagues that handle entire workflows—from research and planning to execution and iteration—with minimal oversight. OpenAI, Anthropic, and global players push reasoning models that excel at complex, multi-step problems. Multimodal integration becomes standard, enabling AI to understand and generate across formats like video synthesis or interactive simulations. Trends include AI accelerating scientific discovery (materials science, biology), AI-native security to counter AI threats, and massive infrastructure builds for energy-efficient datacenters. Challenges loom: talent shortages, ethical bias mitigation, potential economic disruption from automation, and regulatory pushback on high-risk systems. Enterprises must invest in governance frameworks and workforce reskilling. By mid-2026, AI won't just augment jobs—it will redefine collaboration, creativity, and problem-solving at scale, creating abundance in knowledge work while demanding new human-AI partnership models.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI Revolution in 2026"
                        },
                        new
                        {
                            Id = 3,
                            Author = "CodeMaster",
                            CategoryId = 1,
                            Content = "In 2025-2026, developers need machines that handle demanding IDEs, containers, AI/ML workloads, and long compile times without throttling. Top recommendations start with the ASUS ROG Zephyrus G16 or Strix series for their powerful AMD/Intel combos paired with NVIDIA RTX 40-series GPUs—perfect for game dev, CUDA tasks, or heavy rendering. Lenovo ThinkPad X1 Carbon Gen 13 or P-series remain unbeatable for Linux compatibility, exceptional keyboards, durable builds, and 32GB+ RAM configs essential for modern tools like IntelliJ, VS Code with extensions, and Docker. For macOS fans, the latest MacBook Pro M4 Max offers insane battery life and unified memory for seamless Xcode/SwiftUI work. Budget-conscious? Dell XPS 16 or Lenovo Legion deliver solid performance under $1500. Look for at least 32GB RAM, fast NVMe SSDs (2TB+), high-refresh OLED/QHD+ displays, and effective cooling. Prioritize upgradeability where possible and good webcams/mics for remote work. Your laptop should feel like an extension of your brain—fast, reliable, and comfortable for marathon coding sessions.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Laptops for Developers"
                        },
                        new
                        {
                            Id = 4,
                            Author = "QuantumGuru",
                            CategoryId = 1,
                            Content = "Quantum computing leverages quantum mechanics—superposition (qubits in multiple states at once), entanglement (instant correlations), and interference—to tackle problems exponentially harder for classical computers. Unlike binary bits, qubits enable parallel exploration of vast solution spaces. Key applications: simulating molecular interactions for drug/material design, optimizing logistics/finance portfolios, and breaking certain encryptions via Shor's algorithm (though post-quantum crypto is advancing). Current hardware from IBM (Condor, Heron), Google, and IonQ achieves hundreds of qubits with improving fidelity, but noise/decoherence demands sophisticated error correction. Logical qubits (error-protected groups) are the milestone—2025-2026 sees first useful demonstrations. For beginners: imagine searching a maze by exploring all paths simultaneously. Challenges include cryogenic requirements, scalability, and hybrid quantum-classical algorithms. It's not replacing your laptop; it's accelerating specific high-value problems in science and industry.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Computing Explained"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ramsay",
                            CategoryId = 2,
                            Content = "Healthy eating in 2025-2026 focuses on personalization, whole foods, and sustainability. Prioritize vegetables/fruits (half your plate), lean proteins (plant/animal), healthy fats (avocados, nuts, olive oil), and complex carbs (quinoa, sweet potatoes). Trends: functional nutrition with adaptogens, gut-supporting fermented foods, and protein-enriched everyday items (even coffee/snacks). Minimize ultra-processed foods, added sugars, and excessive sodium. Meal prep saves time—batch cook grains/proteins, chop veggies ahead. Hydration: 3-4L water daily, infused for flavor. Mindful eating: chew slowly, no screens, listen to hunger cues. Apps track macros/micros for tailored plans. Balance indulgence—80/20 rule works. Consult RDs for conditions like diabetes or allergies. Consistent small changes compound into lifelong vitality.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Healthy Eating Tips"
                        },
                        new
                        {
                            Id = 8,
                            Author = "FitPro",
                            CategoryId = 2,
                            Content = "A solid morning workout sets energy and mindset for the day. Start with 5-10 min dynamic warm-up (arm circles, leg swings, jumping jacks). Core routine: 20-30 min mix of cardio (jog/brisk walk), strength (bodyweight squats, push-ups, planks, lunges), and mobility (yoga flows). HIIT for efficiency—e.g., 30s burpees, 30s rest, repeat 8x. Add weights if available. Trends: personalized AI-coached sessions via wearables. Finish with stretching/breathing for recovery. Hydrate + protein-rich breakfast post-workout. Consistency beats intensity—aim 5 days/week. Benefits: boosted metabolism, better mood via endorphins, improved focus. Adapt to your level—beginners start shorter. Morning movement builds discipline and resilience.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Workout Routine"
                        },
                        new
                        {
                            Id = 9,
                            Author = "MindfulSoul",
                            CategoryId = 2,
                            Content = "Mental health is as vital as physical in 2025-2026. Stress/anxiety management: daily mindfulness/meditation (apps like Headspace), journaling gratitude, limiting news/social media. Build support—talk to friends, therapy (online accessible). Sleep hygiene: 7-9h, consistent schedule, no screens pre-bed. Exercise and nature exposure reduce cortisol. Trends: teen/young adult focus, burnout recovery programs. Digital detox periods restore attention. Self-compassion over perfectionism. Recognize signs: persistent sadness, withdrawal—seek professional help early. Work boundaries prevent overload. Small daily wins (walks, hobbies) build resilience. Mental health thrives on proactive care, not crisis response.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mental Health Matters"
                        },
                        new
                        {
                            Id = 10,
                            Author = "YogiBear",
                            CategoryId = 2,
                            Content = "Yoga offers holistic benefits: physical (flexibility, strength, balance via poses like downward dog, warrior), mental (stress reduction through breath/pranayama), emotional (mindfulness fosters calm). Regular practice improves posture, joint health, circulation. Styles vary—Hatha for beginners, Vinyasa flow, Yin for deep stretches. 20-60 min sessions 3-5x/week yield results. Trends: augmented classes with wearables tracking form. Combines well with meditation. Benefits extend to better sleep, lower blood pressure, enhanced mood via GABA increase. Accessible anywhere—no fancy gear needed. Start slow, listen to body, use props. Yoga builds body awareness and inner peace for modern life.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Benefits of Yoga"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Dreamer",
                            CategoryId = 2,
                            Content = "Quality sleep (7-9h) is foundational. Science-backed tips: consistent schedule—even weekends. Dark, cool (60-67°F), quiet room—blackout curtains, earplugs, white noise. No caffeine after 2pm, limit alcohol. Wind-down: no screens 1h pre-bed (blue light blocks melatonin), read or journal instead. Evening routine: light dinner, herbal tea, stretching. Track with wearables for patterns. Address issues: if insomnia, CBT-I over pills. Naps <30 min early afternoon. Benefits: sharper cognition, stronger immunity, better mood/weight control. Prioritize sleep—it's recovery time for brain/body.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleep Better Tonight"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Lockhead",
                            CategoryId = 3,
                            Content = "2025-2026 travel favors meaningful, less-crowded spots. Antarctica cruises boom for pristine nature. Asia's secondary cities (e.g., lesser-known Japan towns) grow fast. Europe: shoulder-season shoulder-season for moderate weather/climate adaptation. Wellness retreats in Costa Rica, Morocco. Nostalgic U.S. Route 66 centennial trips. Food-focused: coffee/culinary tours in emerging spots. Sustainable choices: eco-lodges, rail over flights. Personalization via AI planning. Destinations align with passions—hiking, culture, relaxation—for deeper connections.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Travel Destinations"
                        },
                        new
                        {
                            Id = 14,
                            Author = "EuroNomad",
                            CategoryId = 3,
                            Content = "Budget backpacking in Europe thrives with Eurail passes, hostels, street food. Plan shoulder seasons for savings/crowds. Must-visits: Eastern Europe (Poland, Czechia) cheaper than West. Apps: Rome2Rio, Hostelworld. Tips: pack light (carry-on only), use city cards, walk/cycle. Eat local markets. Safety: secure valuables, share itinerary. Cultural immersion over tourist traps. Sustainable: trains over planes. Europe offers history, variety, affordability for epic adventures on a budget.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Backpacking in Europe"
                        },
                        new
                        {
                            Id = 15,
                            Author = "AsiaExplorer",
                            CategoryId = 3,
                            Content = "Off-beaten-path Asia: Bhutan for happiness focus, lesser-visited Thailand islands, Vietnam's highlands, Japan's countryside. Indonesia's lesser-known islands for diving. Tips: local transport, homestays for authenticity. Respect customs. Sustainable tourism key—avoid overtourism. Budget-friendly, rich culture/nature. Emerging spots offer tranquility, unique experiences away from crowds.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hidden Gems in Asia"
                        },
                        new
                        {
                            Id = 16,
                            Author = "SoloWanderer",
                            CategoryId = 3,
                            Content = "Solo travel builds confidence. Safety: research destinations, share plans, use trusted apps (Maps.me offline). Accommodation: well-reviewed, central. Night: avoid isolated areas, trust instincts. Money: multiple cards, minimal cash. Connect: join group tours/meetups. Health: insurance, meds, vaccinations. Embrace freedom but stay aware—solo doesn't mean reckless. Empowering and rewarding.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Solo Travel Safety Tips"
                        },
                        new
                        {
                            Id = 18,
                            Author = "PeakClimber",
                            CategoryId = 3,
                            Content = "Mountain trekking preparation: fitness build-up (hikes, cardio), gear (good boots, layers, poles), acclimatization for altitude. Popular: Nepal Annapurna, Patagonia Torres del Paine. Safety: guides for remote, weather checks. Benefits: stunning views, mental clarity, achievement. Pack light, leave no trace. Adventure with respect for nature.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mountain Trekking Guide"
                        },
                        new
                        {
                            Id = 19,
                            Author = "SimpleLife",
                            CategoryId = 4,
                            Content = "Minimalism evolves to intentional living—quality over quantity, digital declutter (fewer apps/notifications), sustainable choices. 2025-2026 trends: digital minimalism for focus, one-in-one-out rules, capsule wardrobes. Benefits: reduced stress, financial freedom, environmental impact. Start small: declutter spaces, curate possessions. Intentionality creates calm amid chaos.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minimalism in 2025"
                        },
                        new
                        {
                            Id = 20,
                            Author = "TimeMaster",
                            CategoryId = 4,
                            Content = "Productivity 2025-2026: slow productivity (fewer tasks, deep focus), time-blocking, Pomodoro with breaks. Tools: distraction blockers, AI assistants for routine. Eliminate multitasking. Prioritize: Eisenhower matrix. Habits: morning routines, no-meeting days. Sustainable output beats burnout. Track progress, adjust. Get more done meaningfully.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Productivity Hacks"
                        },
                        new
                        {
                            Id = 21,
                            Author = "InteriorPro",
                            CategoryId = 4,
                            Content = "Budget home decor: multifunctional furniture, neutral palettes + accents, plants for life. Trends: sustainable materials, minimalist with personality. DIY shelves, thrifted finds. Lighting layers for ambiance. Declutter first—less stuff, better flow. Create cozy, functional spaces reflecting you.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Home Decor Ideas"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Cinephile",
                            CategoryId = 5,
                            Content = "2025 must-watch: innovative blockbusters, indie gems, AI-influenced storytelling. Trends: immersive experiences, limited series crossovers. Diverse narratives, visual spectacle. From sci-fi epics to emotional dramas—cinema evolves with tech and culture.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Movies of 2025"
                        },
                        new
                        {
                            Id = 26,
                            Author = "GamerX",
                            CategoryId = 5,
                            Content = "2025 games: AI-generated worlds, cloud gaming boom, immersive narratives. Trends: mobile-first, social features. Indie standouts, AAA spectacles. Genres blend—RPGs with survival. Gaming as social/activity hub.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Video Games 2025"
                        },
                        new
                        {
                            Id = 27,
                            Author = "MusicLover",
                            CategoryId = 5,
                            Content = "Fresh 2025 tracks: genre fusions, AI-assisted production, viral sensations. Playlists personalize discovery. Artists experiment—live-streamed creations. Add diverse sounds to your rotation for inspiration.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Music Releases"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Bookworm",
                            CategoryId = 5,
                            Content = "Page-turners 2025: thrillers, sci-fi exploring AI, self-growth. Diverse voices, immersive worlds. Mix fiction/non-fiction for balance. Reading builds empathy, knowledge. Curate based on mood.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book Recommendations"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.HasOne("BlogWebsite.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.HasOne("BlogWebsite.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
