// <auto-generated />
using System;
using BlogWebsite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113134340_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about tech and gadgets",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Health tips and news",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Travel guides and experiences",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "People lifestyle and stuffs.",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports media and all.",
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great article! Learned a lot about tech.",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Very helpful health tips, thanks!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Content = "I want to visit these places ASAP!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserName = "Charlie"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Theon",
                            CategoryId = 1,
                            Content = "Stay updated with the latest technology trends for 2025.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Latest Tech Trends 2025"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ada Lovelace",
                            CategoryId = 1,
                            Content = "How artificial intelligence is shaping the future.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI Revolution in 2026"
                        },
                        new
                        {
                            Id = 3,
                            Author = "CodeMaster",
                            CategoryId = 1,
                            Content = "Top picks for coding and development in 2025.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Laptops for Developers"
                        },
                        new
                        {
                            Id = 4,
                            Author = "QuantumGuru",
                            CategoryId = 1,
                            Content = "A beginner's guide to quantum computing.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Computing Explained"
                        },
                        new
                        {
                            Id = 5,
                            Author = "NetWizard",
                            CategoryId = 1,
                            Content = "The evolution of mobile networks.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "5G vs 6G: What's Next?"
                        },
                        new
                        {
                            Id = 6,
                            Author = "SecureOne",
                            CategoryId = 1,
                            Content = "Protect yourself in the digital age.",
                            ImageUrl = "/images/Posts/Cybersecurity Tips 2025.jfif",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Tips 2025"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ramsay",
                            CategoryId = 2,
                            Content = "Learn how to eat healthy and maintain your lifestyle.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Healthy Eating Tips"
                        },
                        new
                        {
                            Id = 8,
                            Author = "FitPro",
                            CategoryId = 2,
                            Content = "Start your day with energy and strength.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Workout Routine"
                        },
                        new
                        {
                            Id = 9,
                            Author = "MindfulSoul",
                            CategoryId = 2,
                            Content = "Tips for managing stress and anxiety.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mental Health Matters"
                        },
                        new
                        {
                            Id = 10,
                            Author = "YogiBear",
                            CategoryId = 2,
                            Content = "Improve flexibility and inner peace.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Benefits of Yoga"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Dreamer",
                            CategoryId = 2,
                            Content = "Science-backed tips for quality sleep.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleep Better Tonight"
                        },
                        new
                        {
                            Id = 12,
                            Author = "HydroMan",
                            CategoryId = 2,
                            Content = "Why water is your best friend.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hydration and Health"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Lockhead",
                            CategoryId = 3,
                            Content = "Check out the most amazing travel destinations this year.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Travel Destinations"
                        },
                        new
                        {
                            Id = 14,
                            Author = "EuroNomad",
                            CategoryId = 3,
                            Content = "Budget tips for an epic European adventure.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Backpacking in Europe"
                        },
                        new
                        {
                            Id = 15,
                            Author = "AsiaExplorer",
                            CategoryId = 3,
                            Content = "Off-the-beaten-path locations you must visit.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hidden Gems in Asia"
                        },
                        new
                        {
                            Id = 16,
                            Author = "SoloWanderer",
                            CategoryId = 3,
                            Content = "How to travel alone confidently.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Solo Travel Safety Tips"
                        },
                        new
                        {
                            Id = 17,
                            Author = "BeachLover",
                            CategoryId = 3,
                            Content = "Paradise beaches around the world.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Beaches 2025"
                        },
                        new
                        {
                            Id = 18,
                            Author = "PeakClimber",
                            CategoryId = 3,
                            Content = "Prepare for your next hiking adventure.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mountain Trekking Guide"
                        },
                        new
                        {
                            Id = 19,
                            Author = "SimpleLife",
                            CategoryId = 4,
                            Content = "Live more with less.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minimalism in 2025"
                        },
                        new
                        {
                            Id = 20,
                            Author = "TimeMaster",
                            CategoryId = 4,
                            Content = "Get more done in less time.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Productivity Hacks"
                        },
                        new
                        {
                            Id = 21,
                            Author = "InteriorPro",
                            CategoryId = 4,
                            Content = "Transform your space on a budget.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Home Decor Ideas"
                        },
                        new
                        {
                            Id = 22,
                            Author = "StyleIcon",
                            CategoryId = 4,
                            Content = "What to wear this year.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fashion Trends 2025"
                        },
                        new
                        {
                            Id = 23,
                            Author = "HabitBuilder",
                            CategoryId = 4,
                            Content = "Small changes, big results.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Building Good Habits"
                        },
                        new
                        {
                            Id = 24,
                            Author = "MoneyWise",
                            CategoryId = 4,
                            Content = "Manage money like a pro.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Financial Freedom Tips"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Cinephile",
                            CategoryId = 5,
                            Content = "Must-watch films this year.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Movies of 2025"
                        },
                        new
                        {
                            Id = 26,
                            Author = "GamerX",
                            CategoryId = 5,
                            Content = "Games you can't miss.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Video Games 2025"
                        },
                        new
                        {
                            Id = 27,
                            Author = "MusicLover",
                            CategoryId = 5,
                            Content = "Fresh tracks to add to your playlist.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Music Releases"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Bookworm",
                            CategoryId = 5,
                            Content = "Page-turners for every mood.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book Recommendations"
                        },
                        new
                        {
                            Id = 29,
                            Author = "SeriesFan",
                            CategoryId = 5,
                            Content = "Addictive shows worth your time.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "TV Series to Binge"
                        },
                        new
                        {
                            Id = 30,
                            Author = "FunnyGuy",
                            CategoryId = 5,
                            Content = "Laugh out loud with these stand-ups.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy Specials 2025"
                        },
                        new
                        {
                            Id = 31,
                            Author = "CloudGuy",
                            CategoryId = 1,
                            Content = "Intro to cloud services and providers.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cloud Computing Basics"
                        },
                        new
                        {
                            Id = 32,
                            Author = "DevOpsNinja",
                            CategoryId = 1,
                            Content = "CI/CD and automation explained simply.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DevOps for Beginners"
                        },
                        new
                        {
                            Id = 33,
                            Author = "BlockSmith",
                            CategoryId = 1,
                            Content = "Real world blockchain use cases.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blockchain Beyond Crypto"
                        },
                        new
                        {
                            Id = 34,
                            Author = "FutureCoder",
                            CategoryId = 1,
                            Content = "How coding will change in next decade.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Future of Programming"
                        },
                        new
                        {
                            Id = 35,
                            Author = "HealthGeek",
                            CategoryId = 2,
                            Content = "Which workout is better?",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cardio vs Strength Training"
                        },
                        new
                        {
                            Id = 36,
                            Author = "DrWell",
                            CategoryId = 2,
                            Content = "Daily habits for strong immunity.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Boost Your Immunity"
                        },
                        new
                        {
                            Id = 37,
                            Author = "OfficeFit",
                            CategoryId = 2,
                            Content = "Stay healthy with office work.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Desk Job Health Tips"
                        },
                        new
                        {
                            Id = 38,
                            Author = "ZenCoach",
                            CategoryId = 2,
                            Content = "Simple breathing for calm mind.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breathing Exercises"
                        },
                        new
                        {
                            Id = 39,
                            Author = "BudgetNomad",
                            CategoryId = 3,
                            Content = "Travel more by spending less.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Budget Travel Tips"
                        },
                        new
                        {
                            Id = 40,
                            Author = "PackSmart",
                            CategoryId = 3,
                            Content = "Never forget essentials again.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Travel Packing Checklist"
                        },
                        new
                        {
                            Id = 41,
                            Author = "AppTraveler",
                            CategoryId = 3,
                            Content = "Apps every traveler should use.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Travel Apps"
                        },
                        new
                        {
                            Id = 42,
                            Author = "CultureGuide",
                            CategoryId = 3,
                            Content = "Respect local cultures while traveling.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cultural Travel Etiquette"
                        },
                        new
                        {
                            Id = 43,
                            Author = "LifeCoach",
                            CategoryId = 4,
                            Content = "Start your day right.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Routines of Success"
                        },
                        new
                        {
                            Id = 44,
                            Author = "CalmMind",
                            CategoryId = 4,
                            Content = "Reduce screen time stress.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Digital Detox"
                        },
                        new
                        {
                            Id = 45,
                            Author = "BalancePro",
                            CategoryId = 4,
                            Content = "Balance career and personal life.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work Life Balance"
                        },
                        new
                        {
                            Id = 46,
                            Author = "MindTrainer",
                            CategoryId = 4,
                            Content = "Train your mind for consistency.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Self Discipline Hacks"
                        },
                        new
                        {
                            Id = 47,
                            Author = "StreamCritic",
                            CategoryId = 5,
                            Content = "Which streaming service is best?",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "OTT Platforms Compared"
                        },
                        new
                        {
                            Id = 48,
                            Author = "OtakuSensei",
                            CategoryId = 5,
                            Content = "Top anime recommendations.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anime to Watch 2025"
                        },
                        new
                        {
                            Id = 49,
                            Author = "FilmInsider",
                            CategoryId = 5,
                            Content = "How movies are really made.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Behind the Scenes Movies"
                        },
                        new
                        {
                            Id = 50,
                            Author = "SoundWave",
                            CategoryId = 5,
                            Content = "Understand different music styles.",
                            ImageUrl = "/images/posts/default.jpg",
                            PublishedDate = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Music Genres Explained"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.HasOne("BlogWebsite.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.HasOne("BlogWebsite.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
