// <auto-generated />
using System;
using BlogWebsite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about tech and gadgets",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Health tips and news",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Travel guides and experiences",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "People lifestyle and stuffs.",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports media and all.",
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great article! Learned a lot about tech.",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Very helpful health tips, thanks!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Content = "I want to visit these places ASAP!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserName = "Charlie"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Theon",
                            CategoryId = 1,
                            Content = "Stay updated with the latest technology trends for 2025.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Latest Tech Trends 2025"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ada Lovelace",
                            CategoryId = 1,
                            Content = "How artificial intelligence is shaping the future.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI Revolution in 2026"
                        },
                        new
                        {
                            Id = 3,
                            Author = "CodeMaster",
                            CategoryId = 1,
                            Content = "Top picks for coding and development in 2025.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Laptops for Developers"
                        },
                        new
                        {
                            Id = 4,
                            Author = "QuantumGuru",
                            CategoryId = 1,
                            Content = "A beginner's guide to quantum computing.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Computing Explained"
                        },
                        new
                        {
                            Id = 5,
                            Author = "NetWizard",
                            CategoryId = 1,
                            Content = "The evolution of mobile networks.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "5G vs 6G: What's Next?"
                        },
                        new
                        {
                            Id = 6,
                            Author = "SecureOne",
                            CategoryId = 1,
                            Content = "Protect yourself in the digital age.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Tips 2025"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ramsay",
                            CategoryId = 2,
                            Content = "Learn how to eat healthy and maintain your lifestyle.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Healthy Eating Tips"
                        },
                        new
                        {
                            Id = 8,
                            Author = "FitPro",
                            CategoryId = 2,
                            Content = "Start your day with energy and strength.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Workout Routine"
                        },
                        new
                        {
                            Id = 9,
                            Author = "MindfulSoul",
                            CategoryId = 2,
                            Content = "Tips for managing stress and anxiety.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mental Health Matters"
                        },
                        new
                        {
                            Id = 10,
                            Author = "YogiBear",
                            CategoryId = 2,
                            Content = "Improve flexibility and inner peace.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Benefits of Yoga"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Dreamer",
                            CategoryId = 2,
                            Content = "Science-backed tips for quality sleep.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleep Better Tonight"
                        },
                        new
                        {
                            Id = 12,
                            Author = "HydroMan",
                            CategoryId = 2,
                            Content = "Why water is your best friend.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hydration and Health"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Lockhead",
                            CategoryId = 3,
                            Content = "Check out the most amazing travel destinations this year.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Travel Destinations"
                        },
                        new
                        {
                            Id = 14,
                            Author = "EuroNomad",
                            CategoryId = 3,
                            Content = "Budget tips for an epic European adventure.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Backpacking in Europe"
                        },
                        new
                        {
                            Id = 15,
                            Author = "AsiaExplorer",
                            CategoryId = 3,
                            Content = "Off-the-beaten-path locations you must visit.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hidden Gems in Asia"
                        },
                        new
                        {
                            Id = 16,
                            Author = "SoloWanderer",
                            CategoryId = 3,
                            Content = "How to travel alone confidently.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Solo Travel Safety Tips"
                        },
                        new
                        {
                            Id = 17,
                            Author = "BeachLover",
                            CategoryId = 3,
                            Content = "Paradise beaches around the world.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Beaches 2025"
                        },
                        new
                        {
                            Id = 18,
                            Author = "PeakClimber",
                            CategoryId = 3,
                            Content = "Prepare for your next hiking adventure.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mountain Trekking Guide"
                        },
                        new
                        {
                            Id = 19,
                            Author = "SimpleLife",
                            CategoryId = 4,
                            Content = "Live more with less.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minimalism in 2025"
                        },
                        new
                        {
                            Id = 20,
                            Author = "TimeMaster",
                            CategoryId = 4,
                            Content = "Get more done in less time.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Productivity Hacks"
                        },
                        new
                        {
                            Id = 21,
                            Author = "InteriorPro",
                            CategoryId = 4,
                            Content = "Transform your space on a budget.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Home Decor Ideas"
                        },
                        new
                        {
                            Id = 22,
                            Author = "StyleIcon",
                            CategoryId = 4,
                            Content = "What to wear this year.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fashion Trends 2025"
                        },
                        new
                        {
                            Id = 23,
                            Author = "HabitBuilder",
                            CategoryId = 4,
                            Content = "Small changes, big results.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Building Good Habits"
                        },
                        new
                        {
                            Id = 24,
                            Author = "MoneyWise",
                            CategoryId = 4,
                            Content = "Manage money like a pro.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Financial Freedom Tips"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Cinephile",
                            CategoryId = 5,
                            Content = "Must-watch films this year.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Best Movies of 2025"
                        },
                        new
                        {
                            Id = 26,
                            Author = "GamerX",
                            CategoryId = 5,
                            Content = "Games you can't miss.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Video Games 2025"
                        },
                        new
                        {
                            Id = 27,
                            Author = "MusicLover",
                            CategoryId = 5,
                            Content = "Fresh tracks to add to your playlist.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Music Releases"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Bookworm",
                            CategoryId = 5,
                            Content = "Page-turners for every mood.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book Recommendations"
                        },
                        new
                        {
                            Id = 29,
                            Author = "SeriesFan",
                            CategoryId = 5,
                            Content = "Addictive shows worth your time.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "TV Series to Binge"
                        },
                        new
                        {
                            Id = 30,
                            Author = "FunnyGuy",
                            CategoryId = 5,
                            Content = "Laugh out loud with these stand-ups.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy Specials 2025"
                        });
                });

            modelBuilder.Entity("BlogWebsite.Models.Comment", b =>
                {
                    b.HasOne("BlogWebsite.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.HasOne("BlogWebsite.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogWebsite.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogWebsite.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
