using BlogWebsite.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace BlogWebsite.Database
{
    public class AppDbContext : IdentityDbContext<AppUser>
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Comment> Comments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        { 
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Category>().HasData(
        new Category { Id = 1, Name = "Technology", Description = "All about tech and gadgets" },
        new Category { Id = 2, Name = "Health", Description = "Health tips and news" },
        new Category { Id = 3, Name = "Travel", Description = "Travel guides and experiences" },
        new Category { Id = 4, Name = "Lifestyle", Description = "People lifestyle and stuffs." },
        new Category { Id = 5, Name = "Entertainment", Description = "Sports media and all." }

                );
            modelBuilder.Entity<Post>().HasData(
      // Category 1: Tech (10 posts)
      new Post { Id = 1, Title = "Latest Tech Trends 2025", Content = "As we head into late 2025 and look toward 2026, technology continues its rapid evolution, driven primarily by advancements in artificial intelligence, sustainable computing, and connectivity. Agentic AI—systems that autonomously plan, reason, and execute multi-step tasks—has moved from hype to enterprise reality, with Deloitte and Gartner highlighting how organizations are embedding these agents into workflows for everything from customer service to supply chain optimization. Multimodal AI, processing text, images, video, and audio seamlessly, powers more intuitive tools like real-time translation and creative assistants. Edge computing reduces latency for IoT and autonomous systems, while private 5G/6G networks enable secure industrial applications. Sustainability is huge: AI's energy demands push adoption of nuclear-powered data centers and efficient algorithms. Quantum computing edges closer with error-corrected qubits from IBM and Google, promising breakthroughs in drug discovery and optimization. Cybersecurity evolves with AI-driven threat detection amid rising deepfake risks. For developers and businesses, the key is building 'change fitness'—rapid adaptation through hybrid clouds, upskilling, and ethical AI governance. 2025-2026 marks the shift where tech becomes a true strategic partner, not just a tool.", Author = "Theon", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1 },
      new Post { Id = 2, Title = "AI Revolution in 2026", Content = "2026 promises the deepest phase of the AI revolution yet. Agentic AI will dominate, acting as autonomous digital colleagues that handle entire workflows—from research and planning to execution and iteration—with minimal oversight. OpenAI, Anthropic, and global players push reasoning models that excel at complex, multi-step problems. Multimodal integration becomes standard, enabling AI to understand and generate across formats like video synthesis or interactive simulations. Trends include AI accelerating scientific discovery (materials science, biology), AI-native security to counter AI threats, and massive infrastructure builds for energy-efficient datacenters. Challenges loom: talent shortages, ethical bias mitigation, potential economic disruption from automation, and regulatory pushback on high-risk systems. Enterprises must invest in governance frameworks and workforce reskilling. By mid-2026, AI won't just augment jobs—it will redefine collaboration, creativity, and problem-solving at scale, creating abundance in knowledge work while demanding new human-AI partnership models.", Author = "Ada Lovelace", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1 },
      new Post { Id = 3, Title = "Best Laptops for Developers", Content = "In 2025-2026, developers need machines that handle demanding IDEs, containers, AI/ML workloads, and long compile times without throttling. Top recommendations start with the ASUS ROG Zephyrus G16 or Strix series for their powerful AMD/Intel combos paired with NVIDIA RTX 40-series GPUs—perfect for game dev, CUDA tasks, or heavy rendering. Lenovo ThinkPad X1 Carbon Gen 13 or P-series remain unbeatable for Linux compatibility, exceptional keyboards, durable builds, and 32GB+ RAM configs essential for modern tools like IntelliJ, VS Code with extensions, and Docker. For macOS fans, the latest MacBook Pro M4 Max offers insane battery life and unified memory for seamless Xcode/SwiftUI work. Budget-conscious? Dell XPS 16 or Lenovo Legion deliver solid performance under $1500. Look for at least 32GB RAM, fast NVMe SSDs (2TB+), high-refresh OLED/QHD+ displays, and effective cooling. Prioritize upgradeability where possible and good webcams/mics for remote work. Your laptop should feel like an extension of your brain—fast, reliable, and comfortable for marathon coding sessions.", Author = "CodeMaster", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1 },
      new Post { Id = 4, Title = "Quantum Computing Explained", Content = "Quantum computing leverages quantum mechanics—superposition (qubits in multiple states at once), entanglement (instant correlations), and interference—to tackle problems exponentially harder for classical computers. Unlike binary bits, qubits enable parallel exploration of vast solution spaces. Key applications: simulating molecular interactions for drug/material design, optimizing logistics/finance portfolios, and breaking certain encryptions via Shor's algorithm (though post-quantum crypto is advancing). Current hardware from IBM (Condor, Heron), Google, and IonQ achieves hundreds of qubits with improving fidelity, but noise/decoherence demands sophisticated error correction. Logical qubits (error-protected groups) are the milestone—2025-2026 sees first useful demonstrations. For beginners: imagine searching a maze by exploring all paths simultaneously. Challenges include cryogenic requirements, scalability, and hybrid quantum-classical algorithms. It's not replacing your laptop; it's accelerating specific high-value problems in science and industry.", Author = "QuantumGuru", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1 },
      //new Post { Id = 5, Title = "5G vs 6G: What's Next?", Content = "5G transformed connectivity with speeds up to 10Gbps, ultra-low latency (<1ms in ideal cases), and support for millions of devices per km²—powering smart cities, autonomous vehicles, AR/VR, and private enterprise networks. In 2025-2026, 5G-Advanced adds AI optimization and energy efficiency. 6G, targeting 2030 commercialization but with trials accelerating, aims for terabit speeds, sub-millisecond latency, and integration of communication, sensing, and AI. Terahertz bands enable massive bandwidth; AI-native networks self-optimize; joint communication-sensing allows radar-like environmental mapping. Applications: holographic telepresence, digital twins at scale, brain-computer interfaces. Challenges: spectrum policy, hardware for high frequencies, power consumption. The bridge is 5G evolving into 6G via non-terrestrial networks (satellites) and intelligent surfaces. For users, 6G could mean seamless immersive worlds and real-time global sync—redefining remote work, entertainment, and healthcare.", Author = "NetWizard", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1 },
      //new Post { Id = 6, Title = "Cybersecurity Tips 2025", Content = "Cyber threats in 2025-2026 are AI-amplified: automated phishing, deepfake social engineering, ransomware-as-a-service, and supply-chain attacks. Core tips: Use password managers + passkeys/MFA everywhere (biometrics preferred). Update everything—OS, apps, firmware—to close exploits. Phishing awareness: verify URLs/senders, avoid unsolicited attachments/links, use email filters. Employ reputable EDR/antivirus with behavioral analysis. For personal use: VPN on public Wi-Fi, avoid sharing sensitive data, enable auto-lock. Businesses: Adopt zero-trust (verify every access), segment networks, regular backups (immutable/offline), incident response drills. Train on AI threats like voice cloning. Monitor dark web for leaked credentials. Proactive habits beat recovery—cyber hygiene is as essential as brushing teeth in the digital age.", Author = "SecureOne", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 1, ImageUrl = "/images/Posts/Cybersecurity Tips 2025.jfif" },

      // Category 2: Health (10 posts)
      new Post { Id = 7, Title = "Healthy Eating Tips", Content = "Healthy eating in 2025-2026 focuses on personalization, whole foods, and sustainability. Prioritize vegetables/fruits (half your plate), lean proteins (plant/animal), healthy fats (avocados, nuts, olive oil), and complex carbs (quinoa, sweet potatoes). Trends: functional nutrition with adaptogens, gut-supporting fermented foods, and protein-enriched everyday items (even coffee/snacks). Minimize ultra-processed foods, added sugars, and excessive sodium. Meal prep saves time—batch cook grains/proteins, chop veggies ahead. Hydration: 3-4L water daily, infused for flavor. Mindful eating: chew slowly, no screens, listen to hunger cues. Apps track macros/micros for tailored plans. Balance indulgence—80/20 rule works. Consult RDs for conditions like diabetes or allergies. Consistent small changes compound into lifelong vitality.", Author = "Ramsay", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },
      new Post { Id = 8, Title = "Morning Workout Routine", Content = "A solid morning workout sets energy and mindset for the day. Start with 5-10 min dynamic warm-up (arm circles, leg swings, jumping jacks). Core routine: 20-30 min mix of cardio (jog/brisk walk), strength (bodyweight squats, push-ups, planks, lunges), and mobility (yoga flows). HIIT for efficiency—e.g., 30s burpees, 30s rest, repeat 8x. Add weights if available. Trends: personalized AI-coached sessions via wearables. Finish with stretching/breathing for recovery. Hydrate + protein-rich breakfast post-workout. Consistency beats intensity—aim 5 days/week. Benefits: boosted metabolism, better mood via endorphins, improved focus. Adapt to your level—beginners start shorter. Morning movement builds discipline and resilience.", Author = "FitPro", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },
      new Post { Id = 9, Title = "Mental Health Matters", Content = "Mental health is as vital as physical in 2025-2026. Stress/anxiety management: daily mindfulness/meditation (apps like Headspace), journaling gratitude, limiting news/social media. Build support—talk to friends, therapy (online accessible). Sleep hygiene: 7-9h, consistent schedule, no screens pre-bed. Exercise and nature exposure reduce cortisol. Trends: teen/young adult focus, burnout recovery programs. Digital detox periods restore attention. Self-compassion over perfectionism. Recognize signs: persistent sadness, withdrawal—seek professional help early. Work boundaries prevent overload. Small daily wins (walks, hobbies) build resilience. Mental health thrives on proactive care, not crisis response.", Author = "MindfulSoul", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },
      new Post { Id = 10, Title = "Benefits of Yoga", Content = "Yoga offers holistic benefits: physical (flexibility, strength, balance via poses like downward dog, warrior), mental (stress reduction through breath/pranayama), emotional (mindfulness fosters calm). Regular practice improves posture, joint health, circulation. Styles vary—Hatha for beginners, Vinyasa flow, Yin for deep stretches. 20-60 min sessions 3-5x/week yield results. Trends: augmented classes with wearables tracking form. Combines well with meditation. Benefits extend to better sleep, lower blood pressure, enhanced mood via GABA increase. Accessible anywhere—no fancy gear needed. Start slow, listen to body, use props. Yoga builds body awareness and inner peace for modern life.", Author = "YogiBear", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },
      new Post { Id = 11, Title = "Sleep Better Tonight", Content = "Quality sleep (7-9h) is foundational. Science-backed tips: consistent schedule—even weekends. Dark, cool (60-67°F), quiet room—blackout curtains, earplugs, white noise. No caffeine after 2pm, limit alcohol. Wind-down: no screens 1h pre-bed (blue light blocks melatonin), read or journal instead. Evening routine: light dinner, herbal tea, stretching. Track with wearables for patterns. Address issues: if insomnia, CBT-I over pills. Naps <30 min early afternoon. Benefits: sharper cognition, stronger immunity, better mood/weight control. Prioritize sleep—it's recovery time for brain/body.", Author = "Dreamer", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },
      //new Post { Id = 12, Title = "Hydration and Health", Content = "Water is essential—60% of body, regulates temp, transports nutrients, flushes toxins. Aim 3-4L daily (more if active/hot climate). Signs of dehydration: fatigue, headaches, dark urine. Tips: carry reusable bottle, set reminders, infuse with fruit/herbs for flavor. Electrolytes important during exercise/sweat. Trends: smart bottles track intake. Hydration boosts skin health, digestion, cognition. Coffee/tea count partially, but plain water best. Avoid sugary drinks. Proper hydration enhances energy, mood, performance—simple yet powerful habit.", Author = "HydroMan", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 2 },

      // Category 3: Travel (10 posts)
      new Post { Id = 13, Title = "Top Travel Destinations", Content = "2025-2026 travel favors meaningful, less-crowded spots. Antarctica cruises boom for pristine nature. Asia's secondary cities (e.g., lesser-known Japan towns) grow fast. Europe: shoulder-season shoulder-season for moderate weather/climate adaptation. Wellness retreats in Costa Rica, Morocco. Nostalgic U.S. Route 66 centennial trips. Food-focused: coffee/culinary tours in emerging spots. Sustainable choices: eco-lodges, rail over flights. Personalization via AI planning. Destinations align with passions—hiking, culture, relaxation—for deeper connections.", Author = "Lockhead", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },
      new Post { Id = 14, Title = "Backpacking in Europe", Content = "Budget backpacking in Europe thrives with Eurail passes, hostels, street food. Plan shoulder seasons for savings/crowds. Must-visits: Eastern Europe (Poland, Czechia) cheaper than West. Apps: Rome2Rio, Hostelworld. Tips: pack light (carry-on only), use city cards, walk/cycle. Eat local markets. Safety: secure valuables, share itinerary. Cultural immersion over tourist traps. Sustainable: trains over planes. Europe offers history, variety, affordability for epic adventures on a budget.", Author = "EuroNomad", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },
      new Post { Id = 15, Title = "Hidden Gems in Asia", Content = "Off-beaten-path Asia: Bhutan for happiness focus, lesser-visited Thailand islands, Vietnam's highlands, Japan's countryside. Indonesia's lesser-known islands for diving. Tips: local transport, homestays for authenticity. Respect customs. Sustainable tourism key—avoid overtourism. Budget-friendly, rich culture/nature. Emerging spots offer tranquility, unique experiences away from crowds.", Author = "AsiaExplorer", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },
      new Post { Id = 16, Title = "Solo Travel Safety Tips", Content = "Solo travel builds confidence. Safety: research destinations, share plans, use trusted apps (Maps.me offline). Accommodation: well-reviewed, central. Night: avoid isolated areas, trust instincts. Money: multiple cards, minimal cash. Connect: join group tours/meetups. Health: insurance, meds, vaccinations. Embrace freedom but stay aware—solo doesn't mean reckless. Empowering and rewarding.", Author = "SoloWanderer", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },
      //new Post { Id = 17, Title = "Best Beaches 2025", Content = "Paradise beaches 2025-2026: Seychelles for luxury seclusion, Bali's hidden coves, Portugal's Algarve for Europe access, Australia's Whitsundays. Trends: eco-friendly, less crowded. Activities: snorkeling, yoga retreats. Sustainable: reef-safe sunscreen, no single-use plastics. Beaches offer relaxation, adventure, natural beauty.", Author = "BeachLover", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },
      new Post { Id = 18, Title = "Mountain Trekking Guide", Content = "Mountain trekking preparation: fitness build-up (hikes, cardio), gear (good boots, layers, poles), acclimatization for altitude. Popular: Nepal Annapurna, Patagonia Torres del Paine. Safety: guides for remote, weather checks. Benefits: stunning views, mental clarity, achievement. Pack light, leave no trace. Adventure with respect for nature.", Author = "PeakClimber", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 3 },

      // Category 4: Lifestyle (10 posts)
      new Post { Id = 19, Title = "Minimalism in 2025", Content = "Minimalism evolves to intentional living—quality over quantity, digital declutter (fewer apps/notifications), sustainable choices. 2025-2026 trends: digital minimalism for focus, one-in-one-out rules, capsule wardrobes. Benefits: reduced stress, financial freedom, environmental impact. Start small: declutter spaces, curate possessions. Intentionality creates calm amid chaos.", Author = "SimpleLife", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 4 },
      new Post { Id = 20, Title = "Productivity Hacks", Content = "Productivity 2025-2026: slow productivity (fewer tasks, deep focus), time-blocking, Pomodoro with breaks. Tools: distraction blockers, AI assistants for routine. Eliminate multitasking. Prioritize: Eisenhower matrix. Habits: morning routines, no-meeting days. Sustainable output beats burnout. Track progress, adjust. Get more done meaningfully.", Author = "TimeMaster", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 4 },
      new Post { Id = 21, Title = "Home Decor Ideas", Content = "Budget home decor: multifunctional furniture, neutral palettes + accents, plants for life. Trends: sustainable materials, minimalist with personality. DIY shelves, thrifted finds. Lighting layers for ambiance. Declutter first—less stuff, better flow. Create cozy, functional spaces reflecting you.", Author = "InteriorPro", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 4 },
      // Category 5: Entertainment (10 posts)

      new Post { Id = 25, Title = "Best Movies of 2025", Content = "2025 must-watch: innovative blockbusters, indie gems, AI-influenced storytelling. Trends: immersive experiences, limited series crossovers. Diverse narratives, visual spectacle. From sci-fi epics to emotional dramas—cinema evolves with tech and culture.", Author = "Cinephile", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 5 },
      new Post { Id = 26, Title = "Top Video Games 2025", Content = "2025 games: AI-generated worlds, cloud gaming boom, immersive narratives. Trends: mobile-first, social features. Indie standouts, AAA spectacles. Genres blend—RPGs with survival. Gaming as social/activity hub.", Author = "GamerX", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 5 },
      new Post { Id = 27, Title = "New Music Releases", Content = "Fresh 2025 tracks: genre fusions, AI-assisted production, viral sensations. Playlists personalize discovery. Artists experiment—live-streamed creations. Add diverse sounds to your rotation for inspiration.", Author = "MusicLover", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 5 },
      new Post { Id = 28, Title = "Book Recommendations", Content = "Page-turners 2025: thrillers, sci-fi exploring AI, self-growth. Diverse voices, immersive worlds. Mix fiction/non-fiction for balance. Reading builds empathy, knowledge. Curate based on mood.", Author = "Bookworm", PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0), CategoryId = 5 }
      
      
  );
            modelBuilder.Entity<Comment>().HasData(
                 new Comment
                 {
                     Id = 1,
                     UserName = "Alice",
                     Content = "Great article! Learned a lot about tech.",
                     CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0),
                     PostId = 1
                 },
        new Comment
        {
            Id = 2,
            UserName = "Bob",
            Content = "Very helpful health tips, thanks!",
            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0),
            PostId = 2
        },
        new Comment
        {
            Id = 3,
            UserName = "Charlie",
            Content = "I want to visit these places ASAP!",
            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0),
            PostId = 3
        }
                );
        }
    }

}
